project_id = "nofx-local-starter"

[api]
enabled = true
port = 50002

[db]
port = 50000

[studio]
port = 50004

[analytics]
enabled = true
port = 50001
backend = "postgres"


[inbucket]
enabled = true
port = 50003
