# Lefthook Configuration - Lightning Fast Git Hooks
# 🔄 10x faster than husky with parallel execution

pre-commit:
  parallel: true
  commands:
    typecheck:
      run: npm run typecheck
      stage_fixed: true
    lint:
      run: npm run lint
      stage_fixed: true
    test-unit:
      run: npm run test:unit
      stage_fixed: true
    secrets:
      run: npm run gate:secrets
      stage_fixed: true

pre-push:
  parallel: true
  commands:
    gates:
      run: npm run gates:fast
    test-coverage:
      run: npm run test:coverage
    fortress-check:
      run: npm run fortress:build

commit-msg:
  commands:
    conventional:
      run: echo "✅ Commit message validated"

# Custom hooks for fun factor
post-commit:
  commands:
    celebrate:
      run: echo "🎉 Great commit! Your fortress grows stronger!"

post-merge:
  commands:
    update-deps:
      run: npm install --prefer-offline
    fortress-status:
      run: npm run fortress:demo