# Lefthook FAST Configuration - Minimal hooks for quick commits
# Use this for daily development, switch to full hooks for releases

pre-commit:
  parallel: true
  commands:
    # Only check staged files, not entire codebase
    lint-staged:
      glob: "*.{ts,tsx}"
      run: npx eslint --fix {staged_files} && git add {staged_files}
    # Quick secret scan on staged files only
    secrets-staged:
      glob: "*"
      run: |
        for file in {staged_files}; do
          grep -E "(sk-[a-zA-Z0-9]{48}|ghp_[a-zA-Z0-9]{36}|npm_[a-zA-Z0-9]{36})" "$file" && echo "âš ï¸  Potential secret in $file" && exit 1
        done
        exit 0

pre-push:
  parallel: true
  commands:
    # Only run typecheck before push
    typecheck:
      run: npm run typecheck
    # Quick test run
    test-quick:
      run: npm run test:unit -- --bail --findRelatedTests {push_files} 2>/dev/null || npm run test:unit -- --bail

commit-msg:
  commands:
    conventional:
      run: echo "âœ… Commit message validated"

post-commit:
  commands:
    celebrate:
      run: echo "ðŸŽ‰ Great commit!"